### ISSUE TITLE
常见问题样式不正常

### ISSUE THREAD

**Issue by tobelogin** [mc-player-admin/web#2]
常见问题的页面左边的文字鼠标不移上去看不见，页眉显示不正常（f12里把背景图片关了就看起来正常了），希望能解决一下
电脑端edge浏览器
![养蛊-2023-07-04-22-34-11](https://github.com/mc-player-admin/web/assets/108188072/b57bdd8d-9715-49c4-b05a-1432b6829a17)

**Comment by litfa** [comment]
[暂时移除暗色模式](https://github.com/mc-player-admin/web/commit/2b623d406a6dc9aedb91ef8b447ecbf063707647) 后续考虑添加暗色主题
