### ISSUE TITLE
为“千万别点”按钮提点建议

### ISSUE THREAD

**Issue by tobelogin** [mc-player-admin/web#8]
如题，不希望能被采纳，但是能被采纳也不错
1. rickroll（谁没被骗过呢）
2. 一点小小的卡顿惊喜【[https://cznull.github.io/vsbm](url)】
3. 让整个页面的按钮、链接什么的全部失效
4. 一瞬间打开数个标签页
5. 点了之后提示“已成功撤销您的白名单”，但只是提(xia)示(hu)提(xia)示(hu)而已
6. 疯狂弹出对话框，让网页无法操作
7. 关闭窗口

**Comment by tobelogin** [comment]
咦，好像来晚了……

**Comment by alongw** [comment]
《 Chrome 已阻止弹出窗口 》
